name: OWASP ZAP DAST Scan

on:
  push:
    branches: ["main"]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start Express App
        run: |
          nohup node app.js &
          sleep 15

      # Create false-positive suppression rules
      - name: Create Ignore Rules
        run: |
          mkdir -p zap-rules

          printf "10027\tIGNORE\t(.*)\n" > zap-rules/rules.tsv
          printf "10096\tIGNORE\t(.*)\n" >> zap-rules/rules.tsv

      # Run OWASP ZAP Baseline Scan
      - name: Run ZAP Baseline Scan
        run: |
          mkdir -p zap-reports

          chmod -R 777 zap-reports
          chmod -R 777 zap-rules
          chmod -R 777 $PWD

          docker run --rm \
            --network host \
            -v $PWD:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:3000 \
            -r /zap/wrk/zap-reports/report.html \
            -J /zap/wrk/zap-reports/report.json \
            -c /zap/wrk/zap-rules/rules.tsv \
            -m 5

      # Fail pipeline if High Risk alerts exist
      - name: Check High Risk Alerts
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

          HIGH=$(jq '[.site[0].alerts[] | select(.riskdesc | contains("High"))] | length' zap-reports/report.json)

          echo "High Risk Alerts: $HIGH"

          if [ "$HIGH" -gt 0 ]; then
            echo "High Risk Vulnerabilities Found!"
            exit 1
          else
            echo "No High Risk Vulnerabilities Found."
          fi

      # Upload reports
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-reports